### PR TITLE
Add alias to lambda deploy

### PR DESCRIPTION
**Pull request by jlsheehan**
Hi!

Thanks for your excellent plugin, I have been using it for beanstalk and lambda deployments.  When I do a deployLambda I also like to create an alias so it makes it easy to roll back if you need to.

Please consider my changes.

Thanks!

Jeff Sheehan

### CODE REVIEW

**Comment by davidmoten** [comment]
Oh can rebase your PR on master so can get travis working again? Just need to pick up the change from oraclejdk8 to openjdk8 in .travis.yml.

**Comment by jlsheehan** [comment]
Thanks I have not done that before.  I tested with 1 function which was fine but unfortunately had to put in some string checks on the alias because it kept getting bounced with special characters.  I can put some extra notes in doco if you like.

Jeff

**Comment by davidmoten** [comment]
>Thanks I have not done that before

Do this:
```
git checkout master
git pull
git checkout YOUR_BRANCH
git rebase master
git push -f origin YOUR_BRANCH
```

**Comment by jlsheehan** [comment]
>>Thanks I have not done that before ...

@davidmoten that should be all done, build is passing now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by davidmoten** [comment]
Thanks for the contribution! 0.2.21 released to Maven Central

**Pull request merged**
